### ISSUE TITLE
Suggestion on how to fix the game lagging while displaying chunks

### ISSUE THREAD

**Issue by Adatta1276** [1upCommunity/PyCraft#28]
Hi, I saw on the README that you pointed out the game freezes while loading chunks.

What I think you should do is add a render distance feature. If you've played Minecraft, you would know that there is a value
called render_distance that basically detect the player's position in the world, and then renders a certain number of chunks so that the game does not lag. Else, if the world is infinitely generated, and the render distance is set to infinite (as it is now), it could cause the game to freeze like anything or even crash the game. Please implement this feature so that the game runs as expected.

Thanks,
@Adatta1276

**Comment by Adatta1276** [comment]
Also, did you try implementing the feature so that the inside faces and sides/edges of the cube are not rendered? I guess you've already done this since this is a feature of Minecraft, but can you confirm?

**Comment by somePythonProgrammer** [comment]
Yes I did!

**Comment by somePythonProgrammer** [comment]
That feature was added very recently, like yesterday!

**Comment by Adatta1276** [comment]
Ok, thanks for letting me know
