### ISSUE TITLE
Add your name to the Contributors list!

### ISSUE THREAD

**Issue by somePythonProgrammer** [1upCommunity/PyCraft#5]
If You've contributed to this repository in any way, add your name to the contributors list!

Example usage:

> @all-contributors add @somePythonProgrammer for Code, Ideas

**Comment by somePythonProgrammer** [comment]
@all-contributors are you there?

**Comment by somePythonProgrammer** [comment]
OK. You're there.

**Comment by somePythonProgrammer** [comment]
#### Oh. The spelling mistake.
@all-contributors add @somePythonProgrammer for Code, Ideas

**Comment by somePythonProgrammer** [comment]
Yay!

**Comment by somePythonProgrammer** [comment]
@all-contributors add @somePythonProgrammer for infra

**Comment by somePythonProgrammer** [comment]
@all-contributors add @somePythonProgrammer for content

**Comment by somePythonProgrammer** [comment]
@all-contributors add @somePythonProgrammer for maintenance

**Comment by somePythonProgrammer** [comment]
@all-contributors add @somePythonProgrammer for userTesting

**Comment by somePythonProgrammer** [comment]
@all-contributors please add @deepsourcebot for code

**Comment by somePythonProgrammer** [comment]
@all-contributors add @Sreehari521 for code (@Sreehari521 this is just a test!)

**Comment by e-coders** [comment]
@all-contributors can you add @somePythonProgrammer for code, idea

**Comment by DevaanshPathak** [comment]
Can I be added I have merged pull request and am working on chunk loader

**Comment by DevaanshPathak** [comment]
@all-contributers add @DevaanshPathak for fixing bugs

**Comment by DevaanshPathak** [comment]
@all-contributors add DevaanshPathak for fixing bugs

**Comment by DevaanshPathak** [comment]
@all-contributors can you add @DevaanshPathak for fixing bugs and code

**Comment by DevaanshPathak** [comment]
Contributor bot metadata corrupted closing issue

**Comment by somePythonProgrammer** [comment]
We need to fix this!
