### ISSUE TITLE
The game hangs while loading chunks.

### ISSUE THREAD

**Issue by somePythonProgrammer** [1upCommunity/PyCraft#54]
**Describe the bug**
The FPS meter goes lower than 1.0 while loading chunks.

**To Reproduce**
1. Run the code.
2. Wait, and keep checking the FPS meter on the bottom left.

**Expected behavior**
We need to add multiprocessing or threading for efficiency.

**Desktop**
 - OS: Windows 10
 - NVIDIA GTX Graphics card: 2GB
 - Processor: intel 11th gen i5: six cores
 - 8GB RAM

**Comment by somePythonProgrammer** [comment]
@1upCommunity/everyone I've made a new GLFWRemake branch to address this issue. we will be switching to GLFW. There, we can (somehow) use threading and multiple contexts to fix the rendering issue by putting it in a thread. (It aint as easy as it looks)
[StackOverflow question](https://stackoverflow.com/questions/71716836/how-to-add-to-a-pyopengl-vbo-from-another-thread)
[Khronos topic](https://community.khronos.org/t/how-to-add-to-a-pyopengl-vbo-from-another-thread/108484)

**Comment by somePythonProgrammer** [comment]
Join the python discord and go to help-rice for the question I put there: [LINK](https://discord.gg/python)

**Comment by somePythonProgrammer** [comment]
@1upCommunity/everyone I just updated the code. It doesn't hang while rendering now, but it doesn't show anything.

[StackOverflow question](https://stackoverflow.com/questions/71716836/how-to-add-to-a-pyopengl-vbo-from-another-thread)
[Khronos topic](https://community.khronos.org/t/how-to-add-to-a-pyopengl-vbo-from-another-thread/108484)

**Comment by DevaanshPathak** [comment]
@somePythonProgrammer You have implemented multi threading but no open-gl rendering I will send you something in discord refer to that

**Comment by DevaanshPathak** [comment]
@somePythonProgrammer you cannot add multiprocessing as python currently supports only 1 core

**Comment by DevaanshPathak** [comment]
We need something like this I have created a new branch and am implementing this to fix

`import threading
import os
  
def task1():
    print("Task 1 assigned to thread: {}".format(threading.current_thread().name))
    print("ID of process running task 1: {}".format(os.getpid()))
  
def task2():
    print("Task 2 assigned to thread: {}".format(threading.current_thread().name))
    print("ID of process running task 2: {}".format(os.getpid()))
  
if __name__ == "__main__":
  
    # print ID of current process
    print("ID of process running main program: {}".format(os.getpid()))
  
    # print name of main thread
    print("Main thread name: {}".format(threading.current_thread().name))
  
    # creating threads
    t1 = threading.Thread(target=task1, name='t1')
    t2 = threading.Thread(target=task2, name='t2')  
  
    # starting threads
    t1.start()
    t2.start()
  
    # wait until all threads finish
    t1.join()
    t2.join()`

**Comment by DevaanshPathak** [comment]
@somePythonProgrammer I got it working on my pc so basically every pc of i3 / ryzen 3 and above have 4 threads so i took the processes of our software and classified it by ranks of most clocks per second in a thread being used so I made the app divide the selected process in other threads and use a little bit more cache memory I will do a final check tomorrow and add my code to the new branch "Adding-Multi-Thread" So you can check it there and also I will make a pull request so then you can merge the branches

**Comment by DevaanshPathak** [comment]
Also the game will try to use more of the ram as I gave the python vm permission to use 45% of free memory that can optimize it also we need to optimize out texture more. Good Night , I will do the work tomorrow.

**Comment by Super45coder** [comment]
I am not that good at coding. Is there anything I can help with, like designing the website?

**Comment by DevaanshPathak** [comment]
> I am not that good at coding. Is there anything I can help with, like designing the website?

You can start designing a website from where people can download the game and do it in a new repo

**Comment by somePythonProgrammer** [comment]
I've updated the renderer: now it's multithreaded! Look at `core/renderer.py`. We're making progress towards fixing the issue!

**Comment by somePythonProgrammer** [comment]
The only problem is that it only renders 3 faces correctly. All others are glitched.

**Comment by somePythonProgrammer** [comment]
https://stackoverflow.com/questions/73192775/opengl-vbo-textures-not-working-when-loaded-from-a-thread

**Comment by somePythonProgrammer** [comment]
@1upCommunity/everyone  Good news! I just fixed the threaded renderer!

**Comment by DevaanshPathak** [comment]
Renderer fixed closing issue

**Comment by somePythonProgrammer** [comment]
Only the renderer is fixed, we still need to work on the terrain generation, so

**Comment by somePythonProgrammer** [comment]
@1upCommunity/everyone The chunk block computation is fixed. Now for the VBO data computation. Also, @cixtor would you mind helping us here?

**Comment by cixtor** [comment]
I am happy to help.

The project, however, seems to be structured in such a way that it only runs in a specific environment, probably Windows, based on the `.bat` file at the root folder. I am on macOS and the app immediately crashes due to a `NSInternalInconsistencyException` → *“NSWindow drag regions should only be invalidated on the Main Thread”*. This has probably something to do with the project dependencies, the Python version, and the restricted environment that is macOS.

A contributor with a Windows machine may be of more help.

**Comment by somePythonProgrammer** [comment]
We'll be adding cross-platform support for PyCraft after we close this issue. So, we need mac users for that.

**Comment by somePythonProgrammer** [comment]
> NSInternalInconsistencyException → “NSWindow drag regions should only be invalidated on the Main Thread”.

I think I know the reason. PyCraft uses multithreading for updating the OpenGL vbo. We don't need to run the glfw.poll_events
