### ISSUE TITLE
Add cross platform support

### ISSUE THREAD

**Issue by somePythonProgrammer** [1upCommunity/PyCraft#66]
Right now, PyCraft only runs on Windows. We need to make it cross-platform. As @cixtor has pointed out in #54, the game doesn't run on MacOS. We need to add a cross-platform dep installer.

**Comment by codingwatching** [comment]
Is this possible to run on android?

**Comment by somePythonProgrammer** [comment]
Not right now. PyCraft is built for desktop systems.
